"""Integration tests for the PDF parser using the sample FIFA match report fixture.

These tests load the pre-generated fixture PDF (sample_match_report.pdf) and
run the full parse_match_report pipeline to verify end-to-end extraction of
lineups, events, and statistics from a realistic FIFA World Cup match report.

Fixture: tests/fixtures/sample_match_report.pdf
Generated by: tests/fixtures/generate_sample_report.py
"""

import os
from pathlib import Path

import pytest

from app.pdf_parser import ParseResult, parse_match_report
from tests.fixtures.generate_sample_report import (
    AWAY_STARTING_XI,
    AWAY_SUBSTITUTES,
    AWAY_TEAM,
    HOME_STARTING_XI,
    HOME_SUBSTITUTES,
    HOME_TEAM,
    MATCH_EVENTS,
    STATISTICS,
    generate_sample_match_report_pdf,
)

FIXTURE_DIR = Path(__file__).parent / "fixtures"
FIXTURE_PDF_PATH = FIXTURE_DIR / "sample_match_report.pdf"


@pytest.fixture
def sample_pdf_bytes() -> bytes:
    """Load the sample match report PDF fixture from disk.

    Falls back to generating on-the-fly if the fixture file doesn't exist.
    """
    if FIXTURE_PDF_PATH.exists():
        return FIXTURE_PDF_PATH.read_bytes()
    # Regenerate if missing
    return generate_sample_match_report_pdf()


@pytest.fixture
def parse_result(sample_pdf_bytes: bytes) -> ParseResult:
    """Parse the sample fixture PDF and return the ParseResult."""
    return parse_match_report(sample_pdf_bytes)


class TestFixtureIntegrity:
    """Verify the fixture PDF exists and is usable."""

    def test_fixture_file_exists(self):
        """The sample_match_report.pdf fixture should exist in the fixtures directory."""
        assert FIXTURE_PDF_PATH.exists(), (
            f"Fixture not found at {FIXTURE_PDF_PATH}. "
            "Run: python -m tests.fixtures.generate_sample_report"
        )

    def test_fixture_file_non_empty(self):
        """The fixture PDF should be non-empty."""
        assert FIXTURE_PDF_PATH.stat().st_size > 0


class TestTeamNameExtraction:
    """Verify team names are correctly extracted from the fixture."""

    def test_home_team_name(self, parse_result: ParseResult):
        """Home team name should be 'Brazil'."""
        assert parse_result.match_data.homeTeam.name == HOME_TEAM

    def test_away_team_name(self, parse_result: ParseResult):
        """Away team name should be 'Serbia'."""
        assert parse_result.match_data.awayTeam.name == AWAY_TEAM


class TestStartingLineupExtraction:
    """Verify starting XI extraction (11 players per team)."""

    def test_home_starting_xi_count(self, parse_result: ParseResult):
        """Home team should have exactly 11 starting players."""
        assert len(parse_result.match_data.homeTeam.startingLineup) == 11

    def test_away_starting_xi_count(self, parse_result: ParseResult):
        """Away team should have exactly 11 starting players."""
        assert len(parse_result.match_data.awayTeam.startingLineup) == 11

    def test_home_player_names_match(self, parse_result: ParseResult):
        """All home starting players should have expected names."""
        expected_names = {name for _, name, _ in HOME_STARTING_XI}
        extracted_names = {p.name for p in parse_result.match_data.homeTeam.startingLineup}
        assert extracted_names == expected_names

    def test_away_player_names_match(self, parse_result: ParseResult):
        """All away starting players should have expected names."""
        expected_names = {name for _, name, _ in AWAY_STARTING_XI}
        extracted_names = {p.name for p in parse_result.match_data.awayTeam.startingLineup}
        assert extracted_names == expected_names

    def test_home_squad_numbers_valid(self, parse_result: ParseResult):
        """All home starting players should have squad numbers between 1 and 99."""
        for player in parse_result.match_data.homeTeam.startingLineup:
            assert 1 <= player.squadNumber <= 99

    def test_away_squad_numbers_valid(self, parse_result: ParseResult):
        """All away starting players should have squad numbers between 1 and 99."""
        for player in parse_result.match_data.awayTeam.startingLineup:
            assert 1 <= player.squadNumber <= 99

    def test_home_positions_valid(self, parse_result: ParseResult):
        """All home starting players should have valid positions."""
        valid_positions = {"GK", "DEF", "MID", "FWD"}
        for player in parse_result.match_data.homeTeam.startingLineup:
            assert player.position in valid_positions

    def test_away_positions_valid(self, parse_result: ParseResult):
        """All away starting players should have valid positions."""
        valid_positions = {"GK", "DEF", "MID", "FWD"}
        for player in parse_result.match_data.awayTeam.startingLineup:
            assert player.position in valid_positions

    def test_home_has_goalkeeper(self, parse_result: ParseResult):
        """Home starting XI should include at least one goalkeeper."""
        gks = [p for p in parse_result.match_data.homeTeam.startingLineup if p.position == "GK"]
        assert len(gks) >= 1

    def test_away_has_goalkeeper(self, parse_result: ParseResult):
        """Away starting XI should include at least one goalkeeper."""
        gks = [p for p in parse_result.match_data.awayTeam.startingLineup if p.position == "GK"]
        assert len(gks) >= 1


class TestSubstituteExtraction:
    """Verify substitutes are extracted for both teams."""

    def test_home_substitutes_extracted(self, parse_result: ParseResult):
        """Home team should have substitutes extracted."""
        assert len(parse_result.match_data.homeTeam.substitutes) > 0

    def test_away_substitutes_extracted(self, parse_result: ParseResult):
        """Away team should have substitutes extracted."""
        assert len(parse_result.match_data.awayTeam.substitutes) > 0

    def test_home_substitute_count(self, parse_result: ParseResult):
        """Home team should have the expected number of substitutes."""
        assert len(parse_result.match_data.homeTeam.substitutes) == len(HOME_SUBSTITUTES)

    def test_away_substitute_count(self, parse_result: ParseResult):
        """Away team should have the expected number of substitutes."""
        assert len(parse_result.match_data.awayTeam.substitutes) == len(AWAY_SUBSTITUTES)

    def test_home_substitute_names(self, parse_result: ParseResult):
        """Home substitute names should match expected values."""
        expected_names = {name for _, name, _ in HOME_SUBSTITUTES}
        extracted_names = {p.name for p in parse_result.match_data.homeTeam.substitutes}
        assert extracted_names == expected_names

    def test_away_substitute_names(self, parse_result: ParseResult):
        """Away substitute names should match expected values."""
        expected_names = {name for _, name, _ in AWAY_SUBSTITUTES}
        extracted_names = {p.name for p in parse_result.match_data.awayTeam.substitutes}
        assert extracted_names == expected_names

    def test_substitutes_have_valid_attributes(self, parse_result: ParseResult):
        """All substitutes should have valid name, squad number, and position."""
        valid_positions = {"GK", "DEF", "MID", "FWD"}
        all_subs = (
            parse_result.match_data.homeTeam.substitutes
            + parse_result.match_data.awayTeam.substitutes
        )
        for player in all_subs:
            assert player.name
            assert 1 <= player.squadNumber <= 99
            assert player.position in valid_positions


class TestMatchEventsExtraction:
    """Verify match events are extracted (goals, cards, substitutions)."""

    def test_events_extracted(self, parse_result: ParseResult):
        """Events list should not be empty."""
        assert len(parse_result.match_data.events) > 0

    def test_goals_extracted(self, parse_result: ParseResult):
        """Should extract at least the 2 goals from the match."""
        goals = [e for e in parse_result.match_data.events if e.type == "goal"]
        assert len(goals) >= 2

    def test_goal_player_name(self, parse_result: ParseResult):
        """Both goals should be attributed to Richarlison."""
        goals = [e for e in parse_result.match_data.events if e.type == "goal"]
        richarlison_goals = [g for g in goals if g.playerName == "Richarlison"]
        assert len(richarlison_goals) >= 2

    def test_goal_minutes(self, parse_result: ParseResult):
        """Goals should have correct minute values (62, 73)."""
        goals = [e for e in parse_result.match_data.events if e.type == "goal"]
        goal_minutes = sorted([g.minute for g in goals])
        assert 62 in goal_minutes
        assert 73 in goal_minutes

    def test_yellow_cards_extracted(self, parse_result: ParseResult):
        """Should extract yellow cards."""
        yellows = [e for e in parse_result.match_data.events if e.type == "yellow_card"]
        assert len(yellows) >= 2

    def test_red_card_extracted(self, parse_result: ParseResult):
        """Should extract the red card."""
        reds = [e for e in parse_result.match_data.events if e.type == "red_card"]
        assert len(reds) >= 1

    def test_substitutions_extracted(self, parse_result: ParseResult):
        """Should extract substitutions with related player names."""
        subs = [e for e in parse_result.match_data.events if e.type == "substitution"]
        assert len(subs) >= 2

    def test_substitution_has_related_player(self, parse_result: ParseResult):
        """Substitution events should include the related player name."""
        subs = [e for e in parse_result.match_data.events if e.type == "substitution"]
        subs_with_related = [s for s in subs if s.relatedPlayerName is not None]
        assert len(subs_with_related) >= 1

    def test_event_team_assignment(self, parse_result: ParseResult):
        """Events should be assigned to the correct teams."""
        events = parse_result.match_data.events
        team_names = {e.teamName for e in events}
        # At least one event should be for each team
        assert HOME_TEAM in team_names or AWAY_TEAM in team_names

    def test_all_event_minutes_valid(self, parse_result: ParseResult):
        """All event minutes should be within valid range (1-120)."""
        for event in parse_result.match_data.events:
            assert 1 <= event.minute <= 120

    def test_all_event_types_valid(self, parse_result: ParseResult):
        """All event types should be one of the valid types."""
        valid_types = {"goal", "yellow_card", "red_card", "substitution"}
        for event in parse_result.match_data.events:
            assert event.type in valid_types


class TestStatisticsExtraction:
    """Verify statistics are extracted with reasonable values."""

    def test_home_possession_extracted(self, parse_result: ParseResult):
        """Home possession should be approximately 59%."""
        possession = parse_result.match_data.homeTeam.statistics.possessionPct
        assert 50 <= possession <= 70  # Allow some tolerance

    def test_away_possession_extracted(self, parse_result: ParseResult):
        """Away possession should be approximately 41%."""
        possession = parse_result.match_data.awayTeam.statistics.possessionPct
        assert 30 <= possession <= 50  # Allow some tolerance

    def test_home_shots_on_target(self, parse_result: ParseResult):
        """Home shots on target should be a positive value."""
        sot = parse_result.match_data.homeTeam.statistics.shotsOnTarget
        assert sot >= 2  # Brazil had 5 shots on target

    def test_away_shots_on_target(self, parse_result: ParseResult):
        """Away shots on target should be non-negative."""
        sot = parse_result.match_data.awayTeam.statistics.shotsOnTarget
        assert sot >= 0

    def test_home_total_shots(self, parse_result: ParseResult):
        """Home total shots should be positive."""
        shots = parse_result.match_data.homeTeam.statistics.totalShots
        assert shots >= 5  # Brazil had 12 total shots

    def test_away_total_shots(self, parse_result: ParseResult):
        """Away total shots should be non-negative."""
        shots = parse_result.match_data.awayTeam.statistics.totalShots
        assert shots >= 0

    def test_home_passes(self, parse_result: ParseResult):
        """Home passes should be a substantial number."""
        passes = parse_result.match_data.homeTeam.statistics.passes
        assert passes >= 400  # Brazil had 548 passes

    def test_away_passes(self, parse_result: ParseResult):
        """Away passes should be a substantial number."""
        passes = parse_result.match_data.awayTeam.statistics.passes
        assert passes >= 200  # Serbia had 372 passes

    def test_home_fouls(self, parse_result: ParseResult):
        """Home fouls should be non-negative."""
        fouls = parse_result.match_data.homeTeam.statistics.fouls
        assert fouls >= 0

    def test_away_fouls(self, parse_result: ParseResult):
        """Away fouls should be non-negative."""
        fouls = parse_result.match_data.awayTeam.statistics.fouls
        assert fouls >= 0

    def test_possession_values_reasonable(self, parse_result: ParseResult):
        """Both possession values should be between 0 and 100."""
        home_poss = parse_result.match_data.homeTeam.statistics.possessionPct
        away_poss = parse_result.match_data.awayTeam.statistics.possessionPct
        assert 0 <= home_poss <= 100
        assert 0 <= away_poss <= 100

    def test_shots_on_target_le_total(self, parse_result: ParseResult):
        """Shots on target should not exceed total shots (when both are extracted)."""
        home = parse_result.match_data.homeTeam.statistics
        away = parse_result.match_data.awayTeam.statistics
        if home.totalShots > 0:
            assert home.shotsOnTarget <= home.totalShots
        if away.totalShots > 0:
            assert away.shotsOnTarget <= away.totalShots


class TestCompleteExtraction:
    """Verify that the full parse succeeds with no missing fields."""

    def test_missing_fields_empty(self, parse_result: ParseResult):
        """A complete FIFA match report should have no missing fields."""
        assert parse_result.missing_fields == [], (
            f"Expected no missing fields, got: {parse_result.missing_fields}"
        )

    def test_match_id_present(self, parse_result: ParseResult):
        """The match data should have a valid matchId (UUID format)."""
        match_id = parse_result.match_data.matchId
        assert match_id is not None
        assert len(match_id) > 0
        # UUID format check (should contain dashes)
        assert "-" in match_id

    def test_parse_result_is_complete_match_data(self, parse_result: ParseResult):
        """The ParseResult should contain a fully populated MatchData object."""
        md = parse_result.match_data
        assert md.homeTeam is not None
        assert md.awayTeam is not None
        assert md.events is not None
        assert md.actualScore is not None
        assert md.homeTeam.statistics is not None
        assert md.awayTeam.statistics is not None
